INSERT INTO grado_academicos(IdGrado, NombreGrado, Abreviatura) VALUES
(1,'Doctor','Dr.'),
(2,'Doctora','Dra.'),
(3,'Profesora','Profa.'),
(4,'Profesor','Profe.'),
(5,'Maestro en Ciencias','M. en C.'),
(6,'Maestro en DGDP','M. en DGDP.'),
(7,'Ingeniero','Ing.'),
(8,'Licenciado','Lic.'),
(9,'L.I.N.','L.I.N.'),
(10,'L.A.E.','L.A.E.'),
(11,'Técnico','Téc.'),
(12,'Civil','C.'),
(13,'Contado Público','C.P.');

INSERT INTO cargos(IdCargo, NombreCargo, DescripcionCargo) VALUES
(1,'Director','Administrar y transmitir información y tomar decisiones'),
(2,'Ingeniero de Proyectos','Ingeniero de proyectos del CMPL'),
(3,'Asistente','Recibir los oficios que entrar al CMPL'),
(4,'Subdirector','Apoyar a la dirección en la toma de decisiones'),
(5,'Jefe de Departamento','Encargado de Departamento'),
(6,'Responsable Técnico de Laboratorio','Responsable de Laboratorio CMPL'),
(7,'Profesor Investigador','Investigador CMPL'),
(8,'Control Escolar','Gestionar la información de los alumnos del CMPL'),
(9,'Ingeniero de Vinculación de Proyectos','Ingeriero de proyectos vinculados'),
(10,'Control y Presupuesto','Control de presupuesto'),
(11,'Analista','Analista CMPL'),
(12,'Banco de Datos','Banco de Datos CMPL'),
(13,'Contabilidad y Presupuesto','Asigna y gestiona recursos que entrar al CMPL'),
(14,'Contabilidad de Vinculados','Contabilidad de proyectos vinculados'),
(15,'Responsable de Activo Fijo','Responsable activo fijo CMPL'),
(16,'Capital Humano','Contratación y nómina'),
(17,'Ingeniero de Enlace con CONUEE','CONUEE'),
(18,'Auxiliar Administrativo','Auxiliar en el área de administración'),
(19,'Ingeniero de Sistemas','Diferentes actividades en el DSBD'),
(20,'Responsable del POA','Persona encargada de las actividades del POA'),
(21,'Protección Civil',NULL),
(22,'Ingreso Auto-Generado y Presupuesto',NULL),
(23,'Proyectos de Investigación',NULL),
(24,'Activo fijo','Contratación y nomina'),
(25,'Representante de Dirección','POA'),
(26,'Encargado de Biblioteca','Bibliotecario'),
(27,'Sin cargo',NULL);

INSERT INTO areas(IdArea, NombreArea, Objetivo) VALUES
(1,'Dirección',NULL),
(2,'Subdirección Técnica y de Vinculación Área Técnica','Realizar proyectos de Producción Más Limpia y Eficiencia Energética, que ayuden a las empresas a prevenir y disminuir la generación de residuos, así como propiciar el uso eficiente de sus recursos.'),
(3,'Subdirección Académica','Formar recursos humanos en producción más limpia, eficiencia energética y otros temas relacionados con el desarrollo sustentable.'),
(4,'Subdirección Técnica y de Vinculación Área Vinculación','Ofertar los servicios del CMP+L, realizar prospección para incrementar la cartera de clientes así como establecer y mentener el contacto con los clientes.'),
(5,'Departamento de Servicios Administrativos y Técnicos','Administrar los recursos asignados al CMP+L.'),
(6,'Unidad de Informática','Realizar el PEDMP y POA así como sus seguimientos trimestrales; coordinar las actividades de los RDs de los diferentes sistemas del CMP+L.'),
(7,'Sala de Juntas','Reuniones'),
(8,'Biblioteca','Biblioteca del CMPL'),
(9,'Vigilancia','Policía'),
(10,'Formatos',NULL),
(11,'Sistema de Gestión Ambiental',NULL),
(12,'Instructivos',NULL),
(13,'Minutas',NULL),
(14,'Mapa de Procesos',NULL),
(15,'Definiciones',NULL),
(16,'Registros',NULL),
(17,'Manual de Organización',NULL),
(18,'Protección Civil',NULL),
(20,'CIDEP',NULL),
(21,'Junta Directiva',NULL);