@extends('plantillas.menu')
@section('content')
    <center>
        <p></p>
        <p></p>
        <h2>Dirección</h2>
        <p></p>
        <p></p>
    </center>
    @include('plantillas.texto')
    @include('plantillas.lista')
    @include('plantillas.archivos')
@endsection